type ResourceBase = {
  id: string;
  title: string;
  topic: string;
  publisher: string;
  url: string;
  summary: string;
  useFor: string;
};
export type Resource = ResourceBase &
  (
    | { format: "Video"; videoId: string }
    | { format: "Guide" | "Course"; previewImage?: string; videoId?: never }
  );
export const resources: Resource[] = [
  {
    id: "mdn-html",
    title: "HTML basics",
    topic: "HTML",
    format: "Guide",
    publisher: "MDN Web Docs",
    url: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Structuring_content/Basic_HTML_syntax",
    summary: "Elements, attributes, document structure, and practice tasks.",
    useFor: "Read after the first document lesson",
  },
  {
    id: "webdev-html",
    title: "Learn HTML",
    topic: "HTML",
    format: "Course",
    publisher: "web.dev",
    url: "https://web.dev/learn/html",
    previewImage: "https://web.dev/learn/html/card.png",
    summary: "A structured course through HTML features and semantics.",
    useFor: "Deepen the guided HTML module",
  },
  {
    id: "mdn-forms",
    title: "HTML forms",
    topic: "HTML",
    format: "Guide",
    publisher: "MDN Web Docs",
    url: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Structuring_content/HTML_forms",
    summary: "Form controls, labels, and data submission concepts.",
    useFor: "Review before building a contact form",
  },
  {
    id: "fcc-html-video",
    title: "HTML Full Course",
    topic: "HTML",
    format: "Video",
    videoId: "kUMe1FH4CHE",
    publisher: "freeCodeCamp.org",
    url: "https://www.youtube.com/watch?v=kUMe1FH4CHE",
    summary: "A video walkthrough of HTML fundamentals and page building.",
    useFor: "Watch alongside the first two lessons",
  },
  {
    id: "webdev-css",
    title: "Learn CSS",
    topic: "CSS",
    format: "Course",
    publisher: "web.dev",
    url: "https://web.dev/learn/css",
    previewImage: "https://web.dev/learn/css/card.png",
    summary: "A chapter-based guide to styling and layout.",
    useFor: "Continue after the HTML portfolio",
  },
  {
    id: "fcc-css-video",
    title: "CSS Full Course",
    topic: "CSS",
    format: "Video",
    videoId: "OXGznpKZ_sA",
    publisher: "freeCodeCamp.org",
    url: "https://www.youtube.com/watch?v=OXGznpKZ_sA",
    summary: "A long-form CSS lesson with worked examples.",
    useFor: "Practice layout after the CSS lesson",
  },
  {
    id: "mdn-js",
    title: "Dynamic scripting with JavaScript",
    topic: "JavaScript",
    format: "Guide",
    publisher: "MDN Web Docs",
    url: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Scripting",
    summary:
      "A learning path for variables, functions, events, and browser behavior.",
    useFor: "Build a solid language foundation",
  },
  {
    id: "fcc-js-video",
    title: "JavaScript Tutorial for Beginners",
    topic: "JavaScript",
    format: "Video",
    videoId: "Zi-Q0t4gMC8",
    publisher: "freeCodeCamp.org",
    url: "https://www.youtube.com/watch?v=Zi-Q0t4gMC8",
    summary: "A beginner-oriented video course for core JavaScript concepts.",
    useFor: "Review concepts before an exercise",
  },
  {
    id: "odin-foundations",
    title: "Foundations",
    topic: "Web path",
    format: "Course",
    publisher: "The Odin Project",
    url: "https://www.theodinproject.com/paths/foundations/courses/foundations",
    summary:
      "Project-driven web foundations including tools, HTML, CSS, and JavaScript.",
    useFor: "Take a complementary project path",
  },
  {
    id: "pro-git",
    title: "Pro Git",
    topic: "Git",
    format: "Guide",
    publisher: "Git SCM",
    url: "https://git-scm.com/book/en/v2",
    summary:
      "The freely available Git book, from first commands to collaboration.",
    useFor: "Understand a command before memorizing it",
  },
  {
    id: "fcc-git-video",
    title: "Git and GitHub for Beginners",
    topic: "Git",
    format: "Video",
    videoId: "RGOj5yH7evk",
    publisher: "freeCodeCamp.org",
    url: "https://www.youtube.com/watch?v=RGOj5yH7evk",
    summary: "A practical Git and GitHub walkthrough.",
    useFor: "Follow while publishing a first repository",
  },
  {
    id: "mdn-a11y",
    title: "HTML accessibility",
    topic: "Accessibility",
    format: "Guide",
    publisher: "MDN Web Docs",
    url: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Accessibility/HTML",
    summary:
      "Practical patterns for semantic HTML, controls, images, and tables.",
    useFor: "Run a manual publishing review",
  },
  {
    id: "python-tutorial",
    title: "The Python Tutorial",
    topic: "Python",
    format: "Guide",
    publisher: "Python Software Foundation",
    url: "https://docs.python.org/3/tutorial/",
    previewImage:
      "https://docs.python.org/3.14/_images/social_previews/summary_tutorial_index_4224eef5.png",
    summary:
      "The official language tutorial with examples and reference links.",
    useFor: "Look up concepts while working through Python quests",
  },
  {
    id: "fcc-python-video",
    title: "Python for Beginners — Full Course",
    topic: "Python",
    format: "Video",
    videoId: "eWRfhZUzrAc",
    publisher: "freeCodeCamp.org",
    url: "https://www.youtube.com/watch?v=eWRfhZUzrAc",
    summary: "A beginner course covering Python syntax and core ideas.",
    useFor: "Follow with your own small Python programs",
  },
  {
    id: "learncpp",
    title: "Learn C++",
    topic: "C++",
    format: "Course",
    publisher: "LearnCpp.com",
    url: "https://www.learncpp.com/",
    summary: "A free, structured introduction to modern C++.",
    useFor: "Work through compiler and language fundamentals",
  },
  {
    id: "fcc-cpp-video",
    title: "C++ Tutorial for Beginners",
    topic: "C++",
    format: "Video",
    videoId: "vLnPwxZdW4Y",
    publisher: "freeCodeCamp.org",
    url: "https://www.youtube.com/watch?v=vLnPwxZdW4Y",
    summary: "An introductory C++ video course.",
    useFor: "Review syntax while practicing in a local compiler",
  },
  {
    id: "typescript-handbook",
    title: "The TypeScript Handbook",
    topic: "TypeScript",
    format: "Guide",
    publisher: "TypeScript",
    url: "https://www.typescriptlang.org/docs/handbook/intro",
    summary: "Official explanations of types, narrowing, functions, and more.",
    useFor: "Read after JavaScript basics",
  },
  {
    id: "react-learn",
    title: "Learn React",
    topic: "React",
    format: "Guide",
    publisher: "React",
    url: "https://react.dev/learn",
    previewImage: "https://react.dev/images/og/learn.png",
    summary:
      "Official lessons on components, state, rendering, and interaction.",
    useFor: "Practice after JavaScript and TypeScript",
  },
];
export const resourceTopics = [
  "All",
  "HTML",
  "CSS",
  "JavaScript",
  "Web path",
  "Git",
  "Accessibility",
  "Python",
  "C++",
  "TypeScript",
  "React",
] as const;
